/**
 * Live HUD widgets backed by the realtime engine (offline simulator in the demo
 * build). Each subscribes individually so only it re-renders per frame, and
 * each labels the data honestly as simulated — never as live market truth.
 */
import { ArrowDownRight, ArrowUpRight, Radio } from 'lucide-react'
import { PULSE_MODE_LABEL, useEngineSnapshot, useLiveAsset } from './realtimeStore'
import './RealtimeWidgets.css'

function signClass(value: number): string {
  return value >= 0 ? 'rt-pos' : 'rt-neg'
}

function formatPct(value: number): string {
  return `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`
}

/** Topbar pulse indicator. Subscribes individually so only it ticks. */
export function PulseIndicator() {
  const snapshot = useEngineSnapshot()
  const running = snapshot.status?.running ?? false
  const label = PULSE_MODE_LABEL[snapshot.status?.mode ?? 'stopped']
  return (
    <span className="rt-indicator" title="Demo pulse is generated by the offline simulator, not a live market feed.">
      <span className={running ? 'rt-pulse-led live' : 'rt-pulse-led'} aria-hidden />
      {label}
    </span>
  )
}

/** A small honest banner stating the feed is simulated. */
function SimulatedBadge({ label }: { label: string }) {
  return (
    <span className="rt-sim-badge" title="Demo build has no live market feed; values are generated by the offline simulator.">
      <span className="rt-dot" aria-hidden />
      {label}
    </span>
  )
}

/** Command Center: realtime pulse state + top simulated movers. */
export function RealtimePulsePanel({ enabled }: { enabled: boolean }) {
  const snapshot = useEngineSnapshot()
  const status = snapshot.status
  const frame = snapshot.frame
  const running = status?.running ?? false
  const modeLabel = PULSE_MODE_LABEL[status?.mode ?? 'stopped']

  const movers = frame
    ? [...frame.assets].sort((a, b) => Math.abs(b.changePct) - Math.abs(a.changePct)).slice(0, 5)
    : []

  return (
    <div className="rt-pulse">
      <div className="rt-pulse-head">
        <span className={running ? 'rt-pulse-led live' : 'rt-pulse-led'} aria-hidden />
        <div>
          <strong>{modeLabel}</strong>
          <em>
            {running
              ? `frame ${frame?.sequence ?? 0} · ${frame?.assets.length ?? 0} assets · ${status?.connectedFeeds.join(', ') || 'simulator'}`
              : 'Pulse paused'}
          </em>
        </div>
        <SimulatedBadge label="Simulated feed" />
      </div>

      {!enabled || !running ? (
        <div className="rt-empty">
          Pulse is paused. Resume it from the command palette (<span className="rt-kbd">⌘K</span> → Toggle Global Pulse).
        </div>
      ) : movers.length === 0 ? (
        <div className="rt-empty">Warming up the simulated feed…</div>
      ) : (
        <ul className="rt-mover-list">
          {movers.map((asset) => (
            <li key={asset.symbol}>
              <span className="rt-mover-symbol">{asset.symbol}</span>
              <span className="rt-mover-price">{asset.price.toLocaleString()}</span>
              <span className={`rt-mover-change ${signClass(asset.changePct)}`}>
                {asset.changePct >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}
                {formatPct(asset.changePct)}
              </span>
              <span className="rt-mover-vel" title="1m volatility velocity (basis points)">
                v {asset.metrics.volatilityVelocity.toFixed(1)}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

/** Market Terminal: live (simulated) readout for the selected symbol. */
export function LiveMarketReadout({ symbol, enabled }: { symbol: string; enabled: boolean }) {
  const asset = useLiveAsset(symbol)

  if (!enabled) {
    return (
      <div className="rt-readout paused">
        <div className="rt-readout-head">
          <Radio size={14} />
          <span>Live readout</span>
          <SimulatedBadge label="Paused" />
        </div>
        <p className="rt-empty">Pulse paused — showing seeded values only. Toggle Global Pulse to animate.</p>
      </div>
    )
  }

  if (!asset) {
    return (
      <div className="rt-readout">
        <div className="rt-readout-head">
          <Radio size={14} />
          <span>Live readout</span>
          <SimulatedBadge label="Simulated live" />
        </div>
        <p className="rt-empty">No simulated frame yet for {symbol}.</p>
      </div>
    )
  }

  return (
    <div className="rt-readout">
      <div className="rt-readout-head">
        <Radio size={14} />
        <span>Live readout · {asset.symbol}</span>
        <SimulatedBadge label="Simulated live" />
      </div>
      <div className="rt-readout-grid">
        <div>
          <span>Price</span>
          <strong>{asset.price.toLocaleString()}</strong>
        </div>
        <div>
          <span>Session</span>
          <strong className={signClass(asset.changePct)}>{formatPct(asset.changePct)}</strong>
        </div>
        <div>
          <span>1m volume</span>
          <strong>{asset.metrics.oneMinuteVolume.toFixed(0)}</strong>
        </div>
        <div>
          <span>Volatility v</span>
          <strong>{asset.metrics.volatilityVelocity.toFixed(1)}</strong>
        </div>
        <div>
          <span>Vol accel</span>
          <strong className={signClass(asset.metrics.volumeAcceleration)}>
            {formatPct(asset.metrics.volumeAcceleration * 100)}
          </strong>
        </div>
        <div>
          <span>Ticks</span>
          <strong>{asset.tickCount}</strong>
        </div>
      </div>
    </div>
  )
}
